export const Variants: { [baseType: string]: { exactId: number; label: string; description?: string; }[]; } = {
  "Road": [ // 0x00
    { exactId: 0, label: "Normal" },
    { exactId: 1, label: "Dirt, with particle" },
    { exactId: 2, label: "Dirt, without particle" },
    { exactId: 3, label: "Smooth" },
    { exactId: 4, label: "Wood" },
    { exactId: 5, label: "Snow" },
    { exactId: 6, label: "Metal grate" },
    { exactId: 7, label: "Normal, but sound cut off" },
  ],
  "Slippery Road 1": [ // 0x01
    { exactId: 0, label: "White sand" },
    { exactId: 1, label: "Dirt, with bright particle" },
    { exactId: 2, label: "Water (unused)" },
    { exactId: 3, label: "Snow (unused)" },
    { exactId: 4, label: "Grass (unused)" },
    { exactId: 5, label: "Yellow sand" },
    { exactId: 6, label: "Sand, without particle" },
    { exactId: 7, label: "Dirt, without particle" },
  ],
  "Weak Offroad": [ // 0x02
    { exactId: 0, label: "Orange sand" },
    { exactId: 1, label: "Dirt" },
    { exactId: 2, label: "Water" },
    { exactId: 3, label: "Grass, with dark particle" },
    { exactId: 4, label: "Sand, with light particle" },
    { exactId: 5, label: "Carpet" },
    { exactId: 6, label: "Gravel" },
    { exactId: 7, label: "Gravel, different impact SFX" },
  ],
  "Offroad": [ // 0x03
    { exactId: 0, label: "Sand" },
    { exactId: 1, label: "Dirt" },
    { exactId: 2, label: "Mud" },
    { exactId: 3, label: "Water, without particle (unused)" },
    { exactId: 4, label: "Grass" },
    { exactId: 5, label: "Sand, with light particle" },
    { exactId: 6, label: "Gravel, different impact SFX" },
    { exactId: 7, label: "Carpet" },
  ],
  "Heavy Offroad": [ // 0x04
    { exactId: 0, label: "Sand" },
    { exactId: 1, label: "Dirt" },
    { exactId: 2, label: "Mud" },
    { exactId: 3, label: "Flowers" },
    { exactId: 4, label: "Grass" },
    { exactId: 5, label: "Snow" },
    { exactId: 6, label: "Sand" },
    { exactId: 7, label: "Dirt, without particle" },
  ],
  "Slippery Road 2": [ // 0x05
    { exactId: 0, label: "Ice" },
    { exactId: 1, label: "Mud, no GFX (unused)" },
    { exactId: 2, label: "Water, no GFX (unused)" },
    { exactId: 3, label: "Water, no GFX (unused)" },
    { exactId: 4, label: "Water, no GFX (unused)" },
    { exactId: 5, label: "Water, no GFX (unused)" },
    { exactId: 6, label: "Normal road, different sound (unused)" },
    { exactId: 7, label: "Normal road, different sound (unused)" },
  ],
  "Boost": [ // 0x06
    { exactId: 0, label: "Default" },
    { exactId: 1, label: "Variant for casino_roulette" },
    { exactId: 2, label: "Unknown" },
    { exactId: 3, label: "Unknown" },
    { exactId: 4, label: "Unknown" },
    { exactId: 5, label: "Unknown" },
    { exactId: 6, label: "Unknown" },
    { exactId: 7, label: "Unknown" },
  ],
  "Boost Ramp": [ // 0x07
    { exactId: 0, label: "Double flip trick" },
    { exactId: 1, label: "Single flip trick" },
    { exactId: 2, label: "Stunt trick (unused)" },
    { exactId: 3, label: "Stunt trick (unused)" },
    { exactId: 4, label: "Stunt trick (unused)" },
    { exactId: 5, label: "Stunt trick (unused)" },
    { exactId: 6, label: "Stunt trick (unused)" },
    { exactId: 7, label: "Stunt trick (unused)" },
  ],
  "Jump Pad": [ // 0x08
    { exactId: 0, label: "Used in GBA Bowser Castle 3" },
    { exactId: 1, label: "Used in SNES Ghost Valley 2" },
    { exactId: 2, label: "Used in GBA Shy Guy Beach" },
    { exactId: 3, label: "Ramps in Mushroom Gorge" },
    { exactId: 4, label: "Bouncy mushrooms in Mushroom Gorge" },
    { exactId: 5, label: "Used in Chain Chomp Wheel" },
    { exactId: 6, label: "Used in DS Yoshi Falls and Funky Stadium" },
    { exactId: 7, label: "Intended for the venice_gondola object (unused)" },
  ],
  "Item Road": [ // 0x09
    { exactId: 0, label: "Unknown" },
    { exactId: 1, label: "Unknown" },
    { exactId: 2, label: "Used on metal grates" },
    { exactId: 3, label: "Unknown, used on wooden paths/grass/mushrooms" },
    { exactId: 4, label: "Unknown (unused)" },
    { exactId: 5, label: "Unknown, used on grass/bushes" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Solid Fall": [ // 0x0A
    { exactId: 0, label: "Sand" },
    { exactId: 1, label: "Sand/underwater" },
    { exactId: 2, label: "Pavement/tiles" },
    { exactId: 3, label: "Ice" },
    { exactId: 4, label: "Dirt" },
    { exactId: 5, label: "Grass" },
    { exactId: 6, label: "Wood" },
    { exactId: 7, label: "Dark sand, with particle" },
  ],
  "Moving Water": [ // 0x0B
    { exactId: 0, label: "Setting 1" },
    { exactId: 1, label: "Setting 2" },
    { exactId: 2, label: "Setting 3" },
    { exactId: 3, label: "Setting 4" },
    { exactId: 4, label: "Setting 5" },
    { exactId: 5, label: "Setting 6" },
    { exactId: 6, label: "Setting 7" },
    { exactId: 7, label: "Setting 8" },
  ],
  "Wall": [ // 0x0C
    { exactId: 0, label: "Normal" },
    { exactId: 1, label: "Rock" },
    { exactId: 2, label: "Metal" },
    { exactId: 3, label: "Wood" },
    { exactId: 4, label: "Ice" },
    { exactId: 5, label: "Bush, with particle" },
    { exactId: 6, label: "Rope" },
    { exactId: 7, label: "Rubber" },
  ],
  "Invisible Wall": [ // 0x0D
    { exactId: 0, label: "No spark and no character wall hit voice" },
    { exactId: 1, label: "Spark and character wall hit voice (unused)" },
    { exactId: 2, label: "Spark and character wall hit voice (unused)" },
    { exactId: 3, label: "Unknown (unused)" },
    { exactId: 4, label: "Unknown (unused)" },
    { exactId: 5, label: "Unknown (unused)" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Item Wall": [ // 0x0E
    { exactId: 0, label: "Unknown" },
    { exactId: 1, label: "Unknown, used on rock walls" },
    { exactId: 2, label: "Unknown, used on metal walls" },
    { exactId: 3, label: "Unknown" },
    { exactId: 4, label: "Unknown (unused)" },
    { exactId: 5, label: "Unknown, used on grass/bushes" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Wall 2": [ // 0x0F
    { exactId: 0, label: "Normal" },
    { exactId: 1, label: "Rock" },
    { exactId: 2, label: "Metal" },
    { exactId: 3, label: "Wood" },
    { exactId: 4, label: "Ice" },
    { exactId: 5, label: "Bush, without particle (unused)" },
    { exactId: 6, label: "Rope" },
    { exactId: 7, label: "Rubber" },
  ],
  "Fall Boundary": [ // 0x10
    { exactId: 0, label: "Air fall" },
    { exactId: 1, label: "Water" },
    { exactId: 2, label: "Lava" },
    { exactId: 3, label: "Icy water, (ice on respawn)" },
    { exactId: 4, label: "Lava, no GFX" },
    { exactId: 5, label: "Burning air fall" },
    { exactId: 6, label: "Quicksand (used in object quicksand)" },
    { exactId: 7, label: "Short fall" },
  ],
  "Cannon Trigger": [ // 0x11
    { exactId: 0, label: "To point 0" },
    { exactId: 1, label: "To point 1" },
    { exactId: 2, label: "To point 2" },
    { exactId: 3, label: "To point 3 (unused)" },
    { exactId: 4, label: "To point 4 (unused)" },
    { exactId: 5, label: "To point 5 (unused)" },
    { exactId: 6, label: "To point 6 (unused)" },
    { exactId: 7, label: "To point 7 (unused)" },
  ],
  "Force Recalculation": [ // 0x12
    { exactId: 0, label: "Default" },
    { exactId: 1, label: "Unknown (unused)" },
    { exactId: 2, label: "Unknown (unused)" },
    { exactId: 3, label: "Unknown (unused)" },
    { exactId: 4, label: "Unknown (unused)" },
    { exactId: 5, label: "Unknown (unused)" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Half-pipe Ramp": [ // 0x13
    { exactId: 0, label: "Default" },
    { exactId: 1, label: "Boost effect applied" },
    { exactId: 2, label: "Unknown (unused)" },
    { exactId: 3, label: "Unknown (unused)" },
    { exactId: 4, label: "Unknown (unused)" },
    { exactId: 5, label: "Unknown (unused)" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Player-only Wall": [ // 0x14
    { exactId: 0, label: "Normal (unused)" },
    { exactId: 1, label: "Rock (unused)" },
    { exactId: 2, label: "Metal (unused)" },
    { exactId: 3, label: "Wood" },
    { exactId: 4, label: "Ice (unused)" },
    { exactId: 5, label: "Bush (unused)" },
    { exactId: 6, label: "Rope (unused)" },
    { exactId: 7, label: "No particle and sound" },
  ],
  "Moving Road": [ // 0x15
    { exactId: 0, label: "Moves west with BeltCrossing and escalator" },
    { exactId: 1, label: "Moves east with BeltCrossing and west with escalator" },
    { exactId: 2, label: "Moves east with BeltEasy" },
    { exactId: 3, label: "Moves west with BeltEasy" },
    { exactId: 4, label: "Rotates around BeltCurveA clockwise" },
    { exactId: 5, label: "Rotates around BeltCurveA counterclockwise" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Sticky Road": [ // 0x16
    { exactId: 0, label: "Wood" },
    { exactId: 1, label: "Gravel, with different impact particle" },
    { exactId: 2, label: "Carpet" },
    { exactId: 3, label: "Dirt, with particle" },
    { exactId: 4, label: "Sand, with different impact/drift sound, without particle" },
    { exactId: 5, label: "Normal, only sound on RR" },
    { exactId: 6, label: "Normal" },
    { exactId: 7, label: "Mud, with particle" },
  ],
  "Road 2": [ // 0x17
    { exactId: 0, label: "Normal, lower pitch sound" },
    { exactId: 1, label: "Carpet" },
    { exactId: 2, label: "Grass, with sound for rDKM" },
    { exactId: 3, label: "Normal, sound for green shroom" },
    { exactId: 4, label: "Grass" },
    { exactId: 5, label: "Glass, with soundd" },
    { exactId: 6, label: "Dirt (unused)" },
    { exactId: 7, label: "Normal, with sound for RR" },
  ],
  "Sound Trigger": [ // 0x18
    { exactId: 0, label: "Setting 1" },
    { exactId: 1, label: "Setting 2" },
    { exactId: 2, label: "Setting 3" },
    { exactId: 3, label: "Setting 4" },
    { exactId: 4, label: "Setting 5" },
    { exactId: 5, label: "Setting 6" },
    { exactId: 6, label: "Setting 7" },
    { exactId: 7, label: "Setting 8" },
  ],
  "Weak Wall": [ // 0x19
    { exactId: 0, label: "Default" },
    { exactId: 1, label: "Unknown (unused)" },
    { exactId: 2, label: "Unknown (unused)" },
    { exactId: 3, label: "Unknown (unused)" },
    { exactId: 4, label: "Unknown (unused)" },
    { exactId: 5, label: "Unknown (unused)" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Effect Trigger": [ // 0x1A
    { exactId: 0, label: "Change shadow to specific index" },
    { exactId: 1, label: "Change shadow to specific index" },
    { exactId: 2, label: "Trigger water splash unlike fall boundary", description: "Needs triggering fall boundary to reuse, else it will never. " },
    { exactId: 3, label: `Activate <a href="https://szs.wiimm.de/cgi/mkw/object?query=starGate" target="_blank">starGate</a>` },
    { exactId: 4, label: "Half-pipe cancellation" },
    { exactId: 5, label: "Coin despawner, used in battle mode" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Item State Modifier": [ // 0x1B
    { exactId: 0, label: "Default" },
    { exactId: 1, label: "Unknown (unused)" },
    { exactId: 2, label: "Unknown (unused)" },
    { exactId: 3, label: "Unknown (unused)" },
    { exactId: 4, label: "Unknown (unused)" },
    { exactId: 5, label: "Unknown (unused)" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Half-pipe Invisible Wall": [ // 0x1C
    { exactId: 0, label: "Default" },
    { exactId: 1, label: "Unknown (unused)" },
    { exactId: 2, label: "Unknown (unused)" },
    { exactId: 3, label: "Unknown (unused)" },
    { exactId: 4, label: "Unknown (unused)" },
    { exactId: 5, label: "Unknown (unused)" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
  "Rotating Road": [ // 0x1D
    { exactId: 0, label: "Carpet, with different impact particle" },
    { exactId: 1, label: "Norma, with different sound, different impact particle (unused)" },
    { exactId: 2, label: "Normal" },
    { exactId: 3, label: "Glass" },
    { exactId: 4, label: "Carpet" },
    { exactId: 5, label: "No sound, or star crash impact sound (unused)", description: `For star crash impact sound, requires <a href="https://szs.wiimm.de/cgi/mkw/object?query=starGate" target="_blank">starGate</a>` },
    { exactId: 6, label: "Sand (unused)" },
    { exactId: 7, label: "Dirt (unused)" },
  ],
  "Special Wall": [ // 0x1E
    { exactId: 0, label: "Cactus", description: "The player will spin out by touching this" },
    { exactId: 1, label: "No sound and particle", description: "Used behind the lavafalls in GV" },
    { exactId: 2, label: "Bouncy wall (unused)", description: "The player will be pushed backwards by touching this at slow speed" },
    { exactId: 3, label: "No sound and particle", description: "Used for the finish line on WGM and KC" },
    { exactId: 4, label: "Rainbow Road railings", description: "Only for RR" },
    { exactId: 5, label: "Mushroom" },
    { exactId: 6, label: "Metal" },
    { exactId: 7, label: "Gate for competitions", description: `Requires <a href="https://szs.wiimm.de/cgi/mkw/object?query=starGate" target="_blank">starGate</a> for soundd` },
  ],
  "Invisible Wall 2": [ // 0x1F
    { exactId: 0, label: "No sound and particle" },
    { exactId: 1, label: "Unknown (unused)" },
    { exactId: 2, label: "Unknown (unused)" },
    { exactId: 3, label: "Unknown (unused)" },
    { exactId: 4, label: "Unknown (unused)" },
    { exactId: 5, label: "Unknown (unused)" },
    { exactId: 6, label: "Unknown (unused)" },
    { exactId: 7, label: "Unknown (unused)" },
  ],
};

// export const SoundTriggerVariants: { [courseId: string]: { label: string; description?: string; }[]; } = {

// };
